/* eslint-disable */
export default {
  A: ['Province Asahan', 'Province Agam'],
  B: [
    'Province Bojonegoro',
    'District Bukittinggi',
    'Banjarnegara',
    'Bodr',
    'Province Banyumas',
    'District Bksia',
    'District Binjai',
    'Bandung',
    'Province Banyuasin',
    'Bksia',
    'Province Blora',
    'Province Boyolali',
    'Province Batu Bara',
    'District Batu',
    'Bantul',
    'District Blitar',
    'Province Bangkalan',
    'Province Batang',
    'Province Bandung Brta',
    'Province Brebes',
    'District Banjar',
    'Province Bondowoso',
    'District Bandung',
    'District Bodr',
    'Province Banyuwangi'
  ],
  C: [
    'Cirebon',
    'Province Cianjur',
    'District Cilegon',
    'District Cimahi',
    'Province Cilacap',
    'Province Ciamis',
    'District Cirebon'
  ],
  D: [
    'Province Demak',
    'Province Deli Serdang',
    'Province Dharmasraya',
    'District Depok',
    'Province Dairi'
  ],
  E: ['Province Empat Lawang'],
  F: [],
  G: [
    'Province Gunung Kidul',
    'Province Grobogan',
    'District Gunungsitoli',
    'Gambir',
    'Province Gresik',
    'Province Garut'
  ],
  H: ['Province Humbang Hasundutan'],
  I: ['Province Indramayu'],
  J: [
    'District Jataka Selatan',
    'District Jataka Brta',
    'Province Jember',
    'Jataka',
    'Province Jepara',
    'District Jataka Pusat',
    'District Jataka Utara',
    'District Jataka Timur',
    'Province Jombang'
  ],
  K: [
    'Province Klaten',
    'Province Kuningan',
    'Province Kendal',
    'Province Kepulauan Mentawai',
    'Province Kediri',
    'Province Karawang',
    'Province Kulon Progo',
    'Province Kepulauan Seribu',
    'Province Karanganyar',
    'Province Kebumen',
    'Province Kudus',
    'Province Karo'
  ],
  L: [
    'Province Labuhanbatu Selatan',
    'Province Lebak',
    'Province Lumajang',
    'Province Lahat',
    'Province Labuhanbatu Utara',
    'District Lubuk Linggau',
    'Province Lima Puluh District',
    'Province Lamongan',
    'Province Labuhanbatu',
    'Province Langkat'
  ],
  M: [
    'District Mojokerto',
    'District Magelang',
    'Province Mandailing Natal',
    'Province Magetan',
    'District Malang',
    'Province Musi Rawas Utara',
    'Province Mojokerto',
    'District Madiun',
    'Province Muara Enim',
    'District Medan',
    'Province Musi Banyuasin',
    'Province Majalengka',
    'Province Musi Rawas'
  ],
  N: [
    'Province Nias Brta',
    'Province Nias Selatan',
    'Province Nganjuk',
    'Province Ngawi',
    'Province Nias Utara',
    'Province Nias'
  ],
  O: [
    'Province Ogan Komering Ulu',
    'Province Ogan Komering Ulu Timur',
    'Province Ogan Ilir',
    'Province Ogan Komering Ulu Selatan',
    'Province Ogan Komering Ilir'
  ],
  P: [
    'Province Padang Lawas Utara',
    'Province Penukal Abab Lematang Ilir',
    'Province Pemalang',
    'District Pematang Siantar',
    'Province Pakpak Bharat',
    'Province Purwakarta',
    'District Pariaman',
    'Province Purbalingga',
    'Province Pesisir Selatan',
    'Province Padang Pariaman',
    'Pangandaran',
    'District Pagar Alam',
    'Province Ponorogo',
    'District Pasuruan',
    'District Padang',
    'District Padang Panjang',
    'Province Pandeglang',
    'Province Pacitan',
    'District Payakumbuh',
    'District Probolinggo',
    'Province Pasaman',
    'District Pekalongan',
    'Province Purworejo',
    'Province Pasaman Brta',
    'Province Pati',
    'District Prabumulih',
    'District Palembang',
    'Province Padang Lawas',
    'Province Pamekasan',
    'District Padang Sidempuan'
  ],
  Q: [],
  R: ['Province Rembang'],
  S: [
    'Province Situbondo',
    'District Sibolga',
    'District Sukabumi',
    'District Surakarta',
    'Province Sumenep',
    'Province Sleman',
    'District Semarang',
    'District Surabaya',
    'Province Serdang Bedagai',
    'Province Solok Selatan',
    'Province Solok',
    'Province Samosir',
    'Province Sukoharjo',
    'District Solok',
    'Province Sijunjung',
    'Province Subang',
    'Surakarta',
    'Province Sumedang',
    'District Salatiga',
    'Province Sragen',
    'Province Sidoarjo',
    'Sukabumi',
    'District Sawah Lunto',
    'Province Sampang',
    'District Serang',
    'Province Simalungun',
    'Serang'
  ],
  T: [
    'District Tangerang',
    'District Tebing Tinggi',
    'Province Tapanuli Selatan',
    'District Tanjung Balai',
    'Province Tapanuli Tengah',
    'Tasikmalaya',
    'Province Tapanuli Utara',
    'District Tegal',
    'Province Tuban',
    'Province Tulungagung',
    'Province Trenggalek',
    'Province Temanggung',
    'District Tasikmalaya',
    'Province Tanah Datar',
    'Province Toba Samosir',
    'District Tangerang Selatan'
  ],
  U: [],
  V: [],
  W: ['Province Wonosobo', 'Province Wonogiri'],
  X: [],
  Y: ['District Yogyakarta'],
  Z: []
}
